str ='hello# world #this is my string programme' 
# print(str)
# p=str[0:10:2]
# print(p)
# print(len(str))
# p=str.capitalize()
# print(p)
# t=str.casefold()
# print(t)
# u=str.upper()
# print(u)
# l=str.lower()
# print(l)
# l=str.count('o')
# print(l)
# c=str.count('e')
# print(c)
# en=str.endswith('me')
# print(en)
# st=str.startswith('h')
# print(st)
# f=str.find('e')
# print(f)
# lo=str.islower()
# print(lo)
# up=str.isupper()
# print(up)
# str1='  '
# space=str1.isspace()
# print(space)
# st=str.split('l')
# print(st)
# st=str.replace('l','m')
# print(st)
# ti=str.title()
# print(ti)
# pro='mt tution this\ not may be\ possible'
# p=pro.title()
# print(p)
# print(p.swapcase())
# so=pro.splitlines()
# print(so)

t='hello world this is string'
print(t)
p=t[-1:10:1]
print(p)